@startuml
interface IPostService {
    CreateAsync(dto:CreatePostDTO) : Task
    GetByIdAsync(id:int) : Task<GetPostsDTO>
    GetAsync(username:string?, postId:int?) : Task<ICollection<Post>>
}
@enduml
